version: "3.5"

services:
  redis:
    hostname: redis-metal-0{{ .Task.Slot }}
    image: docker.io/bitnami/redis-cluster:7.0
    deploy:
      # placement:
      #   constraints:
      #     - 'node.hostname==metal-0{{ .Task.Slot }}'
        # max_replicas_per_node: 1
      mode: replicated
      replicas: 3
    volumes:
      - redis_data:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-metal-01 redis-metal-02 redis-metal-03'

  # redis-init:
  #   image: docker.io/bitnami/redis-cluster:7.0
  #   volumes:
  #     - redis_{{ .Node.Hostname }}_data:/bitnami/redis/data
  #   depends_on:
  #     - redis-node-0
  #     - redis-node-1
  #     - redis-node-2
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDISCLI_AUTH=bitnami'
  #     - 'REDIS_CLUSTER_REPLICAS=1'
  #     - 'REDIS_NODES=redis-metal-01 redis-metal-02 redis-metal-03'
  #     - 'REDIS_CLUSTER_CREATOR=yes'
